export default {
    AbortoSpontaneo: 'aborto_spontaneo',
    AbortoVolontario: 'aborto_volontario',
    Convivenza: 'convivenza',
    Decesso: 'decesso',
    Divorzio: 'divorzio',
    Donna: 'donna',
    Figlio: 'figlio',
    FiglioAdottivo: 'figlio_adottivo',
    Gemelli: 'gemelli',
    Gravidanza: 'gravidanza',
    InformazioneMancante: 'informazione_mancante',
    Matrimonio: 'matrimonio',
    Relazione: 'relazione',
    RelazioneAbuso: 'relazione_abuso',
    RelazioneAmicizia: 'relazione_amicizia',
    RelazioneConflittuale: 'relazione_conflittuale',
    RelazioneDistante: 'relazione_distante',
    RelazioneMoltoVicini: 'relazione_molto_vicini',
    RelazioneNormale: 'relazione_normale',
    Separazione: 'separazione',
    TransgenderDu: 'transgender_du',
    TransgenderUd: 'transgender_ud',
    Uomo: 'uomo',
}